sidebar:
  menu:
    post: '[博客首页](/)'
    wiki: '[个人主页](https://www.chwin.asia)'
    notes: '[关于](/about/)'
    more: '[友人帐](/friends/)'
  wodgets:
    home: search, welcome

search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要 content: true)

footer:
  social:
    GitHub:
      icon: '<img src="https://xaoxuu.com/assets/placeholder/social/08a41b181ce68.svg"/>'
      url: https://github.com/IoriMaboroshi
    Telegram:
      icon: '<img src="/assets/placeholder/social/telegram-app.svg"/>'
      url: https://t.me/IoriMaboroshi
    unsplash:
      icon: '<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABmJLR0QA/wD/AP+gvaeTAAAFV0lEQVRoge2XS2xUVRjHf+fOTGc6bceRAhUoBoHwMCYoJJggG8JCMXGj0UQCG5VHfBEkQMRNcaGJQNQQKxITRRNi4qIbLYlhJwIiIhglxKqJ1vIotp3WzrQzc+/5XMzr3tt7h5nplA39FnfunDnfOf/f/3zn3DswHdNxZ4eaklE7foozHtyPYhNaAPmctO7gvYcS9Z6q/gB7Lz0BqhOkHQGFAALCDUH2cGDlZ/Wcrn4Aey7MRQUOI/KkApC8cPu9AEq6RQIvcmjlX/WYdvIAHWKQuvSCQg4itOSE5oXb70XykwmIpFDypu7tPciXz1iTmX5yAHsvrFCao8Bqu1C786rgPLZVKIFd1LCV9x/5oVYJtQHsPN1ohMJ7RbMPJOQSlRftDVT4tIGZCuk0Lf0GnetGpx5g14UNCt0JssBDjFO0y/nyYNIH8or1wfquqQHYcbbNCAYOCGyeINq35ssDeYIhX5libOfI+r46AYjitXObDdQhkJllHPQS4wupXHkusITSdGTnnT1MR4euHWDn6cWKwBGFrP/21ftZs6Dl1rx1iO9+H2LdO2cAOaVMY1vmk8cv+/X1Bth6PmQ0ma8jsg8Ig5A9tHqK5HpHZNuJwqqlReu3zNCNtzm6LevuF/RKNpoyH6J53r6sWpddyfqH1oV9FlbI/nB21vw0bHF38wTA0s+CvU7Bsm4vgBLt2GcispFKAdpXtEdv/nadTDJNYdNpPakHZvWhNYUKiMSizF+7PPrrsYndPAGiM6Lc+/B9DP8zyEDPDbTWt72ElFgEQkHaHlxA26pFGMrw7OddQoBSinh7K02zWhjsuX5bAQRoXTqX9jXLCDaGEQFdPIZdOr0al3X1505jyV1EYFXcYPfyAAubpuYvRCF6xhUf3TS4nFK56tW5+UXg+7WxCZP7rkDh4VLgPj9ksfGMxVPzDLYvCtDkn1lTDFmK44MBvkkYWOI0T0QQnwLwleF4OOYpTA1f/G1x8rrFS4sNNswxJv0+bgqcGAlyfChEynIKdkNUDuByH6R0ogn8m4aOXzRdvZrdyxSLm2vD+Hk8wMeDDfRmVLFUHK4LoG33lQJ4uV9sp+TMxQRsOis82ibsWGIQD1Um/GrW4NNEmB/HgmUFF9vye6FiAF/3Ha25ixbovgqn+jXPLYSn28HwWZCUKLpGwnw92kBWVK4sHILzpeLYvPb5KwWwvxi62gvul3By1+EsvHtF6O4Tdi2FB+4qpWng1FgDx/9rJGEaeVHiI9jWVtwLXmLKABT72pfQw32vErsyothyTnjsHuHlJTCkAhwbidKTDfkKdp82XnuhulOoSveL7VIC6b6mONmvaJ4dJjYzBLUIdu+FigEoJVfjfi5Nir+nTU26L8XIQJrWOVHC0UB1gl17oWKAybjvyM/nZVIWV/8YIRprYEZbI0ZQVSS42Fb1g8zmYiXu29O883LjJRMZUok0LTMjxFrDKFRZwaXNXOUKeLlYzn2xdZ6Y5xxPCwz3j5McyhCfHSHSFPIVLPkV8TPMH2AK3MdlQjZj0d+bJBINEW+LEAioCYIdR201JVTexSrcd41XMqHUdyyZYezPDC13h2mOh/NjS/4BZy+takqojItewzghbXm2veTEx2GOAMMDaZLDGWKtEcKNtleMWt6FHBOUvpZmc7lYlF1RifnlCWZGGLiWItwYIDbDVlaF0qoUwM9FRynYIcu4L7dw395e6DqeNBlPjhKNNdAcaygZ4BHefzSF4alxH588mWCCCIwm0tzsSzKeNBEtw5UDKNmNUon6uy8eebZPhwm5X0xTkxgYk+RI5qin1umYjumYjum4o+N/cwnWm7WQCiYAAAAASUVORK5CYII="/>'
      url: mailto:thechwinlyu@outlook.com

comments:
  service: waline
  waline:
    js: https://unpkg.com/@waline/client@v2/dist/waline.js
    css: https://unpkg.com/@waline/client@v2/dist/waline.css
    # Waline server address url, you should set this to your own link
    serverURL: https://waline.chwin.asia # waline 地址
    # If false, comment count will only be displayed in post page, not in home page
    commentCount: true
    # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`.
    pageview: false

    # Custom locales
    locale:
      placeholder: 评论一下吧~ # 输入框内提示文字

    # Custom emoji
    emoji: 
      - https://gcore.jsdelivr.net/gh/norevi/waline-blobcatemojis@1.0/blobs
      - https://unpkg.com/@waline/emojis@1.1.0/weibo
      - https://unpkg.com/@waline/emojis@1.1.0/alus
      - https://unpkg.com/@waline/emojis@1.1.0/bilibili
      - https://unpkg.com/@waline/emojis@1.1.0/qq
      - https://unpkg.com/@waline/emojis@1.1.0/tieba
      - https://unpkg.com/@waline/emojis@1.1.0/tw-emoji
      - https://unpkg.com/@waline/emojis@1.1.0/bmoji

article:
  share: [email, link]